# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-02 11:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_blocker', '0002_auto_20170601_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_user_ids',
            field=models.TextField(default='', validators=[django.core.validators.int_list_validator]),
        ),
    ]
